OSGP/Shared

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/EventNotification.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/EventNotificationType.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/HistoryTermType.java, shared/src/main/java/com/alliander/osgp/shared/domain/entities/AbstractEntity.java, shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/ComponentType.java, shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/FunctionalExceptionType.java, shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/OsgpException.java, shared/src/main/java/com/alliander/osgp/shared/hibernate/ImmutableUserType.java, shared/src/main/java/com/alliander/osgp/shared/hibernate/InetAddressUserType.java, shared/src/main/java/com/alliander/osgp/shared/infra/jms/BaseResponseMessageFinder.java, shared/src/main/java/com/alliander/osgp/shared/infra/jms/ResponseMessage.java, shared/src/main/java/com/alliander/osgp/shared/security/AuthenticationTokenProcessingFilter.java
This pull request resolves several SonarQube isses for all modules of Shared project.
=> Resolves SonarQube issues. OSGP/Platform#138 OSGP/Platform#139

shared/src/main/java/com/alliander/osgp/shared/infra/jms/NotificationResponseMessageSender.java
This pull request contains the changed needed for the handle shipmentfile / add smart meter use case.
=> Feature smartmeter add meter

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/SmartMeteringDevice.java
=> Adds smartmetering DTO valueobject

shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/FunctionalExceptionType.java
=> Adds functional exception type for protocoInfo

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/SynchronizeTimeRequest.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/SynchronizeTimeRequestData.java
Renames SynchronizeTimeReads* -> SynchronizeTime*
=> Renames SynchronizeTimeReads* -> SynchronizeTime*

shared/src/main/java/com/alliander/osgp/shared/usermanagement/AccountDates.java, shared/src/main/java/com/alliander/osgp/shared/usermanagement/AddNewOrganisationRequest.java, shared/src/main/java/com/alliander/osgp/shared/usermanagement/ChangeOrganisationRequest.java, shared/src/main/java/com/alliander/osgp/shared/usermanagement/ChangeUser.java, shared/src/main/java/com/alliander/osgp/shared/usermanagement/ChangeUserRequest.java, shared/src/main/java/com/alliander/osgp/shared/usermanagement/Credentials.java, shared/src/main/java/com/alliander/osgp/shared/usermanagement/OrganisationManagementClient.java, shared/src/main/java/com/alliander/osgp/shared/usermanagement/User.java
=> Bug fix 199 Connects to SmartSocietyServices/Webapps#199

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/ActualMeterReads.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/ActualMeterReadsRequest.java
=> Adds license information to actual meter reads files.

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/RelayMap.java
Connects to SmartSocietyServices/Webapps#296
=> Attemps to add alias to constructor

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/ActualMeterReads.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/MeterReads.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/PeriodicMeterReads.java
=> Feat meter reads

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/SmartMeteringDevice.java
=> Feat store security keys

shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/OsgpException.java, shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/TechnicalException.java
=> Adds constructors without cause to OsgpException and TechnicalException.

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/Event.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/EventLogCategory.java
https://smartsocietyservices.atlassian.net/browse/SLIM-256
=> Implementing support for eventCounter

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/SmsDetails.java
https://smartsocietyservices.atlassian.net/browse/SLIM-187
new pull request, due to change in object class name used in other dependent projects.
=> Feat wakeupsms

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/DeviceStatus.java
=> Enlarged getStatus for Elster FLEX-1517

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/Schedule.java
=> Adds extra properties for Elster schedule FLEX-1542

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/Schedule.java
=> Feat flexovl elster flex 1542

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/Configuration.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/Schedule.java
=> Feat flexovl elster flex 1586

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/AbstractPushSetupDto.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/ActivityCalendarDto.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/AlarmNotificationsDto.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/ConfigurationFlagsDto.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/DayProfileDto.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/PushSetupAlarmDto.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/PushSetupSmsDto.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/SpecialDaysRequestDataDto.java
Added some setters/ changed constructor visibility to allow default mapping with Orika Mapper
=> SLIM-435_Changed_some_Dto_objects

shared/src/main/java/com/alliander/osgp/shared/infra/jms/Constants.java, shared/src/main/java/com/alliander/osgp/shared/infra/jms/ProtocolResponseMessage.java, shared/src/main/java/com/alliander/osgp/shared/infra/jms/RetryHeader.java
Return failed messages to Core with retry properties so Core can trigger a scheduled retry.
=> SLIM-472 retries

shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/RsaEncrypterException.java, shared/src/main/java/com/alliander/osgp/shared/security/RSAEncrypterService.java, shared/src/main/java/com/alliander/osgp/shared/security/RsaEncrypterService.java
SLIM-470 Adds RSAEncrypterService which can be used to encrypt or
decrypt data using private and public keys.
=> SLIM-470 Adds RSAEncrypterService

shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/FunctionalExceptionType.java
=> FLEX-1360 Implements devicemodel in admin app

shared/src/main/java/com/alliander/osgp/shared/security/EncryptionService.java, shared/src/test/java/com/alliander/osgp/shared/security/EncryptionServiceTest.java
- removes unneeded temporary file creation
- fixes key size problem
- fixes simple SonarQube issues
=> Fixes encryption service tests.

shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/FunctionalExceptionType.java
=> FLEX-1921 Solves manufacturer check and fetched frontend code

shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/FunctionalExceptionType.java
=> FLEX-1901 Implements add and remove backend for device model firmware

shared/src/main/java/com/alliander/osgp/shared/exceptionhandling/FunctionalExceptionType.java
Renames Firmware -> DeviceFirmware and DeviceModelFirmware -> Firmware
=> FLEX-1944 ~ Refactors Functional exception messages, concerning firmware

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/FirmwareModuleType.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/FirmwareVersionDto.java, shared/src/main/java/com/alliander/osgp/shared/infra/jms/Constants.java
=> FLEX-1357 ~ Adds FirmwareModuleType

CONTRIBUTING.md, README.md
Also removed the header missing line.
=> Update URLs and added link to website

parent-shared/pom.xml, shared/pom.xml, shared/src/main/java/com/alliander/osgp/shared/infra/db/DefaultConnectionPoolFactory.java
- certralizes Hikari Connection Pool in Shared
- adds several settings (like idle timeout and minimum connections)
- splits database connection string into host, port and database name
=> OC-307 ~ Shared HikariCP.

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/SetKeysRequestDto.java
=> SLIM-882 Fixes replace keys test

osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/ChannelElementValuesDto.java, osgp-dto/src/main/java/com/alliander/osgp/dto/valueobjects/smartmetering/MbusChannelElementsDto.java
Extended DTO for writing Mbut attributes during couple to Gateway device.
=> Slim 976 couple unbound connected

osgp-ws-smartmetering/src/main/java/com/alliander/osgp/ws/smartmetering/config/SmartmeteringNotificationWebServiceConfig.java, osgp-ws-smartmetering/src/main/java/com/alliander/osgp/ws/smartmetering/config/SmartmeteringWebServiceConfig.java
=> SLIM-1028 Adds notificationWebserviceConfig

osgp-ws-smartmetering/src/main/resources/schemas/sm-management.xsd
=> SLIM-1443 Deletes result type from findEvents

shared/src/main/java/com/alliander/osgp/shared/security/CertificateHelper.java
SonarQube reported major issues with code that should be refactored to
throw at most one checked exception, or to not declare exceptions that
cannot occur.
Updates CertificateHelper
* Security exceptions are wrapped in the runtime EncrypterException;
these exceptions should probably not even occur in a correctly
configured environment.
* Updates javadocs to be more specific about the type of key and to make
the description of the key type and provider be more generally
applicable than only for signing as used by the OSLP signing server.
* Extracts duplicate key creation lines of code for a byte array key
into methods for creating a private or a public key by bytes.
* Groups private key related methods together, groups public key related
methods together.
=> SLIM-1534 Refactors code throwing exceptions to resolve SQ issues

osgp-ws-smartmetering/src/main/resources/schemas/sm-monitoring.xsd
PeriodicMeterReadsRequestData to dateTime to support time as well, so we
can filter on that.
=> SLIM-1564: Adjusts type of BeginDate and EndDate of

parent-shared/pom.xml, shared/pom.xml, shared/src/main/java/org/opensmartgridplatform/shared/metrics/PrometheusMetricsServer.java
SLIM-1730: Add PrometheusMetricsServer to shared.
=> SLIM-1730: Add PrometheusMetricsServer to shared.
